services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhook_service
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhook_service
      - REDIS_ADDR=redis:6379
      - WORKER_CONCURRENCY=10
      - RETRY_LIMIT=5
      - LOG_RETENTION_HOURS=72
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhook_service
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
